version: '3'

tasks:
  install:
    desc: Install dependencies
    cmds:
      - pnpm install

  build:
    desc: Build
    cmds:
      - pnpm build
    silent: true

  commit:
    desc: Commit code for a specific LeetCode problem
    cmds:
      - >-
        git commit -m "content: add solution for problem No.{{.CLI_ARGS}}"
    silent: true

  test_update:
    desc: Check whether the new version of the npm package broke the build.
    cmds:
      - git switch main
      - git switch {{.CLI_ARGS}} 2>/dev/null || git switch -c {{.CLI_ARGS}}
      - ncu -u -f {{.CLI_ARGS}}
      - task: install
      - task: build
    silent: true
