version: '3'

tasks:
  build_prod:
    desc: Build production site
    cmds:
      - pnpm build
    silent: true

  commit:
    desc: Commit code for a specific LeetCode problem
    cmds:
      - >-
        git commit -m "content: add solution for problem No.{{.CLI_ARGS}}"
    silent: true
